# Generated by Django 5.0.1 on 2026-01-19 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_type', models.CharField(choices=[('salesforce', 'Salesforce'), ('hubspot', 'HubSpot'), ('zoho', 'Zoho CRM')], max_length=50)),
                ('api_url', models.URLField(blank=True, help_text='Base API URL for the CRM', null=True)),
                ('auth_config', models.JSONField(help_text='JSON containing client_id, client_secret, tokens, etc.')),
                ('field_mapping', models.JSONField(blank=True, default=dict, help_text="Mapping from JSON keys to CRM specific fields. E.g. {'website_field': 'CRM_Field'}")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_configurations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'crm_type')},
            },
        ),
    ]
