# Generated by Django 5.0.1 on 2026-01-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmconfiguration',
            name='crm_type',
            field=models.CharField(choices=[('salesforce', 'Salesforce'), ('hubspot', 'HubSpot'), ('zoho', 'Zoho CRM'), ('monday', 'Monday.com')], max_length=50),
        ),
    ]
