# Generated by Django 5.0.1 on 2026-01-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_crmconfiguration_crm_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmconfiguration',
            name='crm_type',
            field=models.CharField(choices=[('salesforce', 'Salesforce'), ('hubspot', 'HubSpot'), ('zoho', 'Zoho CRM'), ('monday', 'Monday.com'), ('pipedrive', 'Pipedrive'), ('dynamics', 'Microsoft Dynamics 365')], max_length=50),
        ),
    ]
